version: '3.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    container_name: elastic
    environment:
      - node.name=elastic
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.name=docker-cluster
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - discovery.type=single-node    
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.12.1
    container_name: kibana
    environment:
      - SERVER_NAME=kibana.localhost
      - ELASTICSEARCH_HOSTS=http://192.168.99.100:9200
    ports:
      - 5601:5601
    networks:
      - elastic
    depends_on: ['elasticsearch']

#  logstash:
#    image: docker.elastic.co/logstash/logstash:7.12.1
#    container_name: logstash
#    networks:
#      - elastic
#    depends_on: ['elasticsearch']

volumes:
  data01:
    driver: local

networks:
  elastic:
    driver: bridge
